### ISSUE TITLE
when build news-ssr app,it appear error

### ISSUE THREAD

**Issue by ChenYCL** [namecheap/ilc-demo-apps#14]
![image](https://user-images.githubusercontent.com/25706676/84380507-a2902a80-ac11-11ea-95e2-6b32232765b4.png)

**Comment by StyleT** [comment]
Hi! We actually not really support Windows as OS for ILC development as all our devs use Linux/macOS. However you can easily submit a PR which adds https://www.npmjs.com/package/cross-env to npm scripts. I think lack of it is the issue here 😉
